### ISSUE TITLE
请问，音频消息怎么发送？

### ISSUE THREAD

**Issue by JesusCracker** [easemob/webim#121]
能不能贴部分代码 谢谢

**Comment by QWK-001** [comment]
addAudioMessage: (message, bodyType) => {
        return (dispatch, getState) => {
            let options = {
                url: message.url,
                headers: {
                    Accept: 'audio/mp3'
                },
               onFileDownloadComplete: function (response) {      //成功之后的回调 
                    let objectUrl = WebIM.utils.parseDownloadResponse.call(WebIM.conn, response)
                    message.url = objectUrl
                    dispatch(Creators.addMessage(message, bodyType))
                },
                onFileDownloadError: function () {     //失败之后的回调
                }
            }
            WebIM.utils.download.call(WebIM.conn, options)
        }
    },
