### ISSUE TITLE
本地调试 3.0 版本  无法正常登陆到 控制台 需要平台的帮助

### ISSUE THREAD

**Issue by zhangxiaowei** [easemob/webim#207]
# 开发环境信息
☁  demo [dev_3.0] ⚡  node -v
v18.9.1

# 项目版本 
demo [dev_3.0]

# 操作步骤
   1.在demo/src/config  更换 WebIMConfig.js 中的 appkey   echo MTE2MzE3MTAyNjExNTc1MyUyM2RlbW8=  | base64 --decode
   2.npm install 
   3.HTTPS=true npm start 
  4.访问：https://localhost:3001/#/login  
  用户名：123456 密码：123456（已在环信后台创建）
# 出现的问题 
   输入用户名与密码 会在浏览器当中 显示登录成功，但是实际上不能够进行跳转
    界面显示截图如下
    
![image](https://user-images.githubusercontent.com/23535450/195046851-0e8a2e21-ac0d-4d36-b7e3-b2d510ca1dab.png)

![image](https://user-images.githubusercontent.com/23535450/195046756-3d4ba140-7934-4b48-8f16-b0fb401432db.png)

![image](https://user-images.githubusercontent.com/23535450/195046692-87511d1a-d8a3-40cb-9f14-5c072ed14aa2.png)

**Comment by Wster11** [comment]
你好,因为安全合规的要求，目前的登录方式仅支持easemob#easeim appkey进行登录体验。如还有其他问题，可以联系管理后台首页的商务经理，获取技术支持服务。

**Comment by zhangxiaowei** [comment]
> 你好，因为安全合规的要求，目前的登录仅支持easemob#easeim appkey进行登录体验。如还有其他问题，可以联系管理后台首页的商务经理，获取技术支持服务。

好的 收到 刚才 在测试过程中 也发现了这个问题 更换 官方 appkey 确实 能在本地正常登录 。
